apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: myrs-ros
spec:
   replicas: 4
   selector:
     matchLabels:
        env: production
#     matchExpressions:
#       - { key: env, operator: In, values: [ testing ] }
#       - { key: country, operator: In, values: [ germany ] }
   template:
      metadata:
         name: myweb-pod
         labels:
            env: production
#            country: germany
#            datacentre: "11"
      spec:
         containers:
         - name: myweb
           image: httpd
